name: frontend-deploy

on:
  push:
    branches: [main]
    paths:
      - 'frontend/taskmanager-ui/**'
      - '.github/workflows/frontend-deploy.yml'

permissions:
  contents: read
  id-token: write   # required for WIF

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: projects/578910743970/locations/global/workloadIdentityPools/github-pool/providers/github-provider
          service_account: artifact-pusher@still-function-494322-d7.iam.gserviceaccount.com

      - uses: google-github-actions/setup-gcloud@v2

      - run: gcloud auth configure-docker europe-west3-docker.pkg.dev

      - name: Build & push image
        working-directory: frontend/taskmanager-ui
        run: |
          gcloud builds submit \
            --tag europe-west3-docker.pkg.dev/still-function-494322-d7/taskmanager/frontend:${{ github.sha }} \
            --region=europe-west3 \
            --default-buckets-behavior=REGIONAL_USER_OWNED_BUCKET \
            --service-account=projects/still-function-494322-d7/serviceAccounts/artifact-pusher@still-function-494322-d7.iam.gserviceaccount.com

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy frontend \
            --image europe-west3-docker.pkg.dev/still-function-494322-d7/taskmanager/frontend:${{ github.sha }} \
            --region europe-west3 \
            --platform managed \
            --port 80 \
            --allow-unauthenticated
